name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Linting (opsional)
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 src --max-line-length=100

      # 5. Run training
      - name: Train model
        run: |
          python src/train.py

      # 6. Run prediction test
      - name: Test prediction
        run: |
          python src/predict.py

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-ml-app .

      # 8. Run container (test inside Docker)
      - name: Run container
        run: |
          docker run --rm my-ml-app
