name: ML Pipeline (DVC + MLflow)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # === 1. Train & Track with MLflow ===
  # === 1. Train & Track with MLflow ===
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] mlflow

      - name: Initialize DVC repository (if missing)
        run: |
          if [ ! -d ".dvc" ]; then
            echo "⚙️ Initializing DVC repo..."
            dvc init --no-scm -q
          else
            echo "✅ DVC already initialized."
          fi

      - name: Run DVC pipeline
        run: |
          echo "🚀 Running DVC pipeline..."
          dvc repro -f || (echo "❌ DVC repro failed!" && exit 1)
          dvc metrics show || echo "ℹ️ No metrics to show."

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl

      - name: Upload MLflow logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/
