name: ML Pipeline (DVC + MLflow)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # === 1. Train & Track with MLflow ===
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] mlflow

      - name: Run DVC pipeline
        run: |
          dvc repro -f
          dvc metrics show

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/model.pkl

      - name: Upload MLflow logs
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: mlruns/

  # === 2. Prediction job ===
  predict:
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: models

      - name: Run prediction
        run: |
          python src/predict.py

  # === 3. Build & Push Docker image ===
  docker:
    runs-on: ubuntu-latest
    needs: [train, predict]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/personality-ml:latest
